# ==============================================================================
# SYSTEMD DAEMON MANAGEMENT MANIFEST
# ==============================================================================
# Description: Reference guide and automation commands for managing background 
#              system daemons / services on Linux (Raspberry Pi OS, Ubuntu, Debian).
# Usage: Keep this file in your repository root as a quick-reference sheet.
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. CORE SERVICE LIFECYCLE MANAGEMENT
# ------------------------------------------------------------------------------

# START: Launch the service immediately in the background
sudo systemctl start p_rover.service

# STOP: Safely terminate the running background process
sudo systemctl stop p_rover.service

# RESTART: Kill the active process and immediately launch a fresh instance
# (Crucial to run after updating your underlying Python/executable code)
sudo systemctl restart p_rover.service

# STATUS: Check if the service is active, running, idling, or crashed
sudo systemctl status p_rover.service


# ------------------------------------------------------------------------------
# 2. BOOT CONFIGURATION (PERSISTENCE)
# ------------------------------------------------------------------------------

# ENABLE: Configure the service to launch automatically whenever the Pi boots up
sudo systemctl enable p_rover.service

# DISABLE: Prevent the service from starting automatically on boot
sudo systemctl disable p_rover.service

# IS-ENABLED: Check whether the service is currently set to start on boot
sudo systemctl is-enabled p_rover.service


# ------------------------------------------------------------------------------
# 3. REGISTRATION AND CONFIGURATION UPDATES
# ------------------------------------------------------------------------------
# Run these whenever you modify the actual structure of your '.service' file.

# RELOAD DAEMON: Force systemd to scan configuration directories for new/edited files
sudo systemctl daemon-reload

# EDIT: Open the service configuration file directly in the default system editor
sudo systemctl edit --full p_rover.service

# PATH REFERENCE: Standard directory where custom systemd service files must live
# /etc/systemd/system/


# ------------------------------------------------------------------------------
# 4. LIVE TELEMETRY AND DIAGNOSTIC LOGGING
# ------------------------------------------------------------------------------
# systemd captures all standard output (print statements) and standard errors.

# STREAM LOGS: Monitor live outputs and print statements in real-time (Follow mode)
# Press Ctrl+C to exit this view.
sudo journalctl -u p_rover.service -f

# RECENT LOGS: View the last 50 lines of logs to debug a recent failure
sudo journalctl -u p_rover.service -n 50 --no-pager

# BOOT LOGS: View all logs generated by the service since the current system boot
sudo journalctl -u p_rover.service -b


# ------------------------------------------------------------------------------
# 5. TROUBLESHOOTING & RECOVERY PIPELINE
# ------------------------------------------------------------------------------

# LIST ALL SERVICES: List all active systemd services currently loaded on the system
sudo systemctl list-units --type=service

# FAILED SERVICES: Identify any system daemons that are currently in a failed state
sudo systemctl --failed

# RESET FAILED: Clear the 'failed' status flag of a service after fixing the underlying bug
sudo systemctl reset-failed robot_mission.service
